(async function () {
  console.log('%cCopyGPT (Copy For ChatGPT Extension) Loaded', 'color: green; font-size: 30px');
  const currentYear = new Date().getFullYear()
  console.log(`
  - Copy Button: Enabled ✅
  - CMD+K Hotkey: Enabled ✅
  - Up Arrow Key: Enabled ✅
  - ✨ AI plagiarism checker: Enabled ✅

  Copyright (c) ${currentYear} Sethu Senthil
  Version: 0.3.1
  https://copygpt.sethusenthil.com
  https://sethusenthil.com
  `)

  const CHAT_TEXT_SELECTOR = '.markdown';
  const CLIPBOARD_CLASS_NAME = 'copy-to-clipboard';


  const showSnackbar = (message, position) => {
    const snack = document.createElement('div');
    snack.classList.add('snackbar');

    if (position) {
      //default position is bottom
      snack.classList.add(position);
    } else {
      snack.classList.add('bottom');
    }

    snack.innerText = message;
    document.body.appendChild(snack);
    snack.classList.add('show');
    setTimeout(function () {
      snack.className = snack.className.replace("show", "");
      snack.remove();
    }, 3000);
  };

  chrome.runtime.onMessage.addListener(function (response, sender, sendResponse) {
    // console.log('response', response);

    if (response.message.documents[0].average_generated_prob >= 0.5) {
      showSnackbar('This text was flagged as AI generated by plagiarism detectors, make some changes before submitting! 🚨', 'top');
    } else {
      showSnackbar('Your text was not flagged by AI detectors! ✅', 'top');
    }
  });

  const copyToClipboard = (str) => {
    chrome.runtime.sendMessage({ message: str });

    navigator.clipboard.writeText(str).then(function () {
      //console.log('Async: Copying to clipboard was successful!');
    }, function (err) {
      console.error('Async: Could not copy text: ', err);
    });
    showSnackbar('Copied to clipboard 📋');
  };


  const intervalId = window.setInterval(async function () {
     if (!document.querySelector('#copygpt-credits')) {
      var textCenterElement = document.querySelector('.text-center');
	  if (textCenterElement == null) {
		textCenterElement = document.querySelector('.text-center.text-xs');
	  }
	  textCenterElement.insertAdjacentHTML('beforeend', '&nbsp; ✨ <a class="underline" id="copygpt-credits" target="_blank" href="https://copygpt.sethusenthil.com/?ref=gptFooter"> Enhanced by CopyGPT</a>')
    }

    const chatContainer = document.querySelector('.flex .flex-col .items-center');

    //console.log('probing for new chat bubbles');
    const chatbubbles = chatContainer.querySelectorAll('main.w-full .border-b');
    //console.log('chatbubbles', chatbubbles);

	//check if it is a plus user
	var plusUser = (chatbubbles.length % 2 === 0) ? false : true;
	
    chatbubbles.forEach((chatbox, i) => {
      //console.log('chatbox', chatbox);
      //first chat box needs to be from user, hence all the even chat bubbles are from bot
	  //plus users will have the first row as model selection
      if ((i>0 && (i % 2 === 0) && plusUser) ||
	      ((i + 1) % 2 === 0 && !plusUser))
	  {
        //it is a chat box from bot
        const addAfter = chatbox.querySelector(CHAT_TEXT_SELECTOR);

        if (chatbox.querySelector(`.${CLIPBOARD_CLASS_NAME}`) === null) {

          addAfter.insertAdjacentHTML('afterend', `<div style="display: flex; align-items: center; color: lightslategray;" class="copy-to-clipboard">
          <p>Copy to Clipboard</p> <img src="https://copygpt.sethusenthil.com/cdn/clipboard-emoji.webp" alt="clipboard emoji" class="emoji"/>
          </div>`);
          chatbox.querySelector(`.${CLIPBOARD_CLASS_NAME}`).addEventListener('click', function () {

            const text = chatbox.querySelector(CHAT_TEXT_SELECTOR).innerText;
            copyToClipboard(text);

          });
        } else {

        }

      }
    });

    if (chatContainer.getAttribute('listener-injected') !== 'true') {

      //console.log('setting event listener cause its not already there')
      document.addEventListener('keydown', function (event) {
        const chatContainer = document.querySelector('.flex .flex-col .items-center');

        if (event.metaKey && event.key === 'k') {
          //console.log('Copy Shortcut Pressed');
          //when command k is pressed
          const chatbubbles = chatContainer.querySelectorAll('main.w-full .border-b');
          if (chatbubbles.length % 2 === 0) {
            //if last chat is from bot
            const lastChatBubble = chatbubbles[chatbubbles.length - 1];
            const text = lastChatBubble.querySelector(CHAT_TEXT_SELECTOR).innerText
            copyToClipboard(text);
          }

        }
        chatContainer.setAttribute('listener-injected', 'true');
      });

      const textarea = document.querySelector('textarea');

      textarea.addEventListener('keydown', function (event) {
        if (event.key === 'ArrowUp') {
          if (chatbubbles.length > 0) {
            let lastSetIndex = chatContainer.getAttribute('last-set-index') ?? 0;
            //console.log('lastSetIndex', lastSetIndex);

            if (lastSetIndex >= chatbubbles.length) {
              lastSetIndex = 0;
            }

            lastSetIndex++;

            const lastChatBubble = chatbubbles[chatbubbles.length - lastSetIndex];
            const text = lastChatBubble.innerText

            textarea.value = text;
            chatContainer.setAttribute('last-set-index', lastSetIndex);
          }
        }
      });
    }
  }, 1000);

  //Check if user is pro
  //JSON.parse(document.querySelector('#__NEXT_DATA__')?.innerHTML)?.props?.pageProps?.serviceAnnouncement?.paied

})();

